name: Build AGS Packages

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  PACKAGES: |
    aylurs-gtk-shell 
      libastal-gjs-git
      libastal-meta
        libastal-git
        libastal-4-git
        libastal-apps-git
        libastal-auth-git
        libastal-battery-git
        libastal-bluetooth-git
        libastal-cava-git
          libcava
        libastal-greetd-git
        libastal-hyprland-git
        libastal-io-git
        libastal-mpris-git
        libastal-network-git
        libastal-notifd-git
        libastal-powerprofiles-git
        libastal-river-git
        libastal-tray-git
          appmenu-glib-translator-git
        libastal-wireplumber-git

jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - run: pacman -Syu --noconfirm git base-devel sudo meson

      - name: Create a non-root user
        run: |
          useradd -m u
          echo "u ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/u
          chown -R u:u .

      - name: Build Astal packages
        run: sudo -u u bash -c "./makepkg.sh `tac <<< $PACKAGES | xargs`"
      - name: Build AGS v3
        run: sudo -u u bash -c "makepkg -D ags -si --noconfirm"

      - run: |
          rm -rf */*-debug-*.pkg.tar.zst
          mkdir -p packages
          mv */*.pkg.tar.zst packages
          find -name '*.pkg.tar.zst'

      - name: Upload packages
        uses: actions/upload-artifact@v4
        with:
          name: packages
          path: packages
