name: Build AUR Packages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - run: pacman -Syu --noconfirm git base-devel sudo meson

      - name: Create a non-root user
        run: |
          useradd -m u
          echo "u ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/u
          chown -R u:u .
      - run: sudo -u u bash -c "./makepkg.sh aylurs-gtk-shell"
      - run: |
          su u
          git clone --branch v3 --recurse-submodules https://github.com/Aylur/ags.git
          cd ags
          meson setup --prefix ~/.local build
          meson install -C build
          ls ~/.local
      
      # - name: Upload 
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: share
      #     path: /.local

